spring.application.name=securevoteledger

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

ethereum.privateKey=0x70144ae4cb5bcf625ca0af3d6458d6e2a1b905705bc9f4069d0be00d2cfb94e5
ethereum.contractAddress=0xE9c0e58c61fddd8E870d625662964E226977fB12
ethereum.rpcUrl=http://127.0.0.1:7545
