spring.application.name=securevoteledger
#spring.datasource.url=jdbc:mysql://localhost:3306/secure_vote_ledger
#spring.datasource.username=root
#spring.datasource.password=dhwni1495
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.datasource.url=jdbc:mysql://root:thhJNwHDqFzHdIeQCzClLKPhgTwifwZJ@shinkansen.proxy.rlwy.net:11308/railway
spring.datasource.username=root
spring.datasource.password=thhJNwHDqFzHdIeQCzClLKPhgTwifwZJ

ethereum.privateKey=0xdd03d2a58aaa2e727a8b5b53a407f099755f49f1186a70398e7b5c9e177d679f
ethereum.contractAddress=0xcC83d3fC52Ff2D5FB6dB43C273fd3070491F49Ab
ethereum.rpcUrl=http://127.0.0.1:7545
