spring.application.name=securevoteledger

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

ethereum.privateKey=${ETH_PRIVATE_KEY}
ethereum.contractAddress=${ETH_CONTRACT_ADDRESS}
ethereum.rpcUrl=${ETH_RPC_URL}
